### ISSUE TITLE
Why do sb1 -> sb2 -> sb3, instead of the more direct sb1 -> sb3?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-sb1-converter#16]
This is just a design question since I'm curious - why was it decided that sb1 projects would be converted  to sb2 projects, then loaded into Scratch 3.0 as though they were sb2 projects? It seems like, since 2.0 is (from my understanding) not really going to be maintained once 3.0 is released, it would make more sense to directly convert from sb1 -> sb3, rather than to have a separate component for sb1 -> sb2.

(What I'm asking here is based on LLK/scratch-vm#1852.)

**Comment by mzgoddard** [comment]
We considered transforming sb1 directly to sb3. We choose to transform to sb2 however on practical merits.

Scratch 2 editor transforms Scratch 1 projects into Scratch 2, but while it does this it leaves some Scratch 1 behaviours that Scratch 3 now has to support. Since sb2 support was implemented first, a series of Scratch 1 2 bugs are fixed in `src/serialization/sb2.js`. Some of the ways Scratch 3 supports those is by making compatible changes to the project while loading it in `src/serialization/sb2.js`. There are also non-bug Scratch 1 to Scratch 3 translations handled by `sb2.js`.

As that work exists in `sb2.js` we want to make use of it while converting sb1 files. We could separate the Scratch 1 conversions that exist in `sb2.js`. Doing so, we would need to retain a way for `sb2.js` to make use of those separated conversions. Creating that interface is likely a lot of work as the conversions are deeply integrated into `sb2.js`. Its a vertically integrated system with Scratch 1 conversions sprinkled around.

Comparatively converting sb1 to sb2 is a lot less work than separating the Scratch 1 bug and non-bug conversions implemented in `sb2.js` and retaining support of those conversions without breaking existing support for scratch 1 projects previously converted by the Scratch 2 editor.

**Comment by towerofnix** [comment]
Awesome, thank you for the explanation! That makes sense - all the conversions in sb2 imports work with sb1, so just converting sb1 -> sb2 is a good way to make use of those conversions.
